name: test
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: DeLaGuardo/setup-clojure@3.5
        with:
          cli: 1.10.3.967
      
      - name: Run tests
        run: clojure -X:run-tests
